<?php
/**
 * Read-only access to the content manifest React Shell exposes.
 *
 * The manifest (contract §1) is generated by the React build and shipped
 * inside gcalls-react-shell; this plugin never declares routes, sections or
 * fields of its own. Everything here degrades to "no editable routes" when
 * React Shell is inactive, too old, or ships no manifest — Preview and Admin
 * turn that into a visible dependency error.
 *
 * @package Gcalls\ContentStudio
 */

declare( strict_types = 1 );

namespace Gcalls\ContentStudio;

defined( 'ABSPATH' ) || exit;

class Manifest {

	/** @var array<string, mixed>|null */
	private static ?array $cache = null;

	/** @return array<string, mixed> Decoded manifest, or [] when unavailable. */
	public static function raw(): array {
		if ( null !== self::$cache ) {
			return self::$cache;
		}
		if ( ! function_exists( 'gcalls_react_shell_content_manifest' ) ) {
			self::$cache = array();
			return self::$cache;
		}
		$manifest    = gcalls_react_shell_content_manifest();
		self::$cache = is_array( $manifest ) && isset( $manifest['pages'] ) && is_array( $manifest['pages'] ) ? $manifest : array();
		return self::$cache;
	}

	public static function available(): bool {
		return ! empty( self::raw()['pages'] );
	}

	/** @return int|null Manifest schema version as shipped, null when unavailable. */
	public static function schema_version(): ?int {
		$raw = self::raw();
		return isset( $raw['schemaVersion'] ) ? (int) $raw['schemaVersion'] : null;
	}

	/**
	 * Pages keyed by route key, in manifest order.
	 *
	 * @return array<string, array<string, mixed>>
	 */
	public static function pages(): array {
		$out = array();
		foreach ( self::raw()['pages'] ?? array() as $page ) {
			if ( ! is_array( $page ) || empty( $page['key'] ) || ! is_string( $page['key'] ) ) {
				continue;
			}
			$out[ $page['key'] ] = $page;
		}
		return $out;
	}

	/** @return array<string, mixed>|null */
	public static function page( string $route ): ?array {
		return self::pages()[ $route ] ?? null;
	}

	public static function route_exists( string $route ): bool {
		return null !== self::page( $route );
	}

	/** Whether the page is open for editing ("editable") rather than read-only ("review"). */
	public static function route_editable( string $route ): bool {
		$page = self::page( $route );
		return null !== $page && 'editable' === ( $page['status'] ?? 'review' );
	}

	public static function route_path( string $route ): string {
		return (string) ( self::page( $route )['path'] ?? '' );
	}

	public static function route_label( string $route ): string {
		return (string) ( self::page( $route )['label'] ?? $route );
	}

	/**
	 * Sections of a page keyed by section key, in manifest order.
	 *
	 * @return array<string, array<string, mixed>>
	 */
	public static function sections( string $route ): array {
		$out  = array();
		$page = self::page( $route );
		foreach ( $page['sections'] ?? array() as $section ) {
			if ( ! is_array( $section ) || empty( $section['key'] ) || ! is_string( $section['key'] ) ) {
				continue;
			}
			$out[ $section['key'] ] = $section;
		}
		return $out;
	}

	public static function section_exists( string $route, string $section ): bool {
		return isset( self::sections( $route )[ $section ] );
	}

	/** @return array<string, array<string, mixed>>|null name => Field, null for an unknown route/section. */
	public static function fields( string $route, string $section ): ?array {
		$def = self::sections( $route )[ $section ] ?? null;
		if ( null === $def ) {
			return null;
		}
		$fields = $def['fields'] ?? array();
		return is_array( $fields ) ? $fields : array();
	}

	/** @return array<string, mixed> */
	public static function defaults( string $route, string $section ): array {
		$def = self::sections( $route )[ $section ] ?? null;
		$d   = $def['defaults'] ?? array();
		return is_array( $d ) ? $d : array();
	}

	/** @return string[] Lower-cased PII_BLOCKED attachment filenames. */
	public static function blocked_media(): array {
		$list = self::raw()['blockedMedia'] ?? array();
		if ( ! is_array( $list ) ) {
			return array();
		}
		return array_values( array_map( static fn( $f ) => strtolower( basename( (string) $f ) ), $list ) );
	}

	/**
	 * The subset the admin editor needs (contract §7): pages, sections,
	 * fields and defaults — nothing else.
	 *
	 * @return array<string, mixed>
	 */
	public static function for_admin(): array {
		$raw = self::raw();
		return array(
			'manifestVersion' => (int) ( $raw['manifestVersion'] ?? MANIFEST_VERSION ),
			'schemaVersion'   => (int) ( $raw['schemaVersion'] ?? SCHEMA_VERSION ),
			'pages'           => array_values( self::pages() ),
		);
	}
}
